# Generated by Django 5.2.17 on 2026-09-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="A full image URL (https://...), or a path under static/, e.g. images/products/shoe-1.jpg",
                max_length=300,
            ),
        ),
    ]
